# Generated by Django 5.2.8 on 2025-12-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawPerson",
            fields=[
                (
                    "nconst",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("primary_name", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RawTitle",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("primary_title", models.CharField(max_length=500)),
                ("start_year", models.IntegerField(db_index=True, null=True)),
                ("genres", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SquidGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SquidRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SquidPerson",
            fields=[
                (
                    "nconst",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.rawperson",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SquidMovie",
            fields=[
                (
                    "tconst",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.rawtitle",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("year", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawPrincipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=100)),
                (
                    "nconst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.rawperson"
                    ),
                ),
                (
                    "tconst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.rawtitle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SquidMovieToGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.squidgenre",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.squidmovie",
                    ),
                ),
            ],
            options={
                "unique_together": {("movie", "genre")},
            },
        ),
        migrations.AddField(
            model_name="squidmovie",
            name="genres",
            field=models.ManyToManyField(
                through="core.SquidMovieToGenre", to="core.squidgenre"
            ),
        ),
        migrations.CreateModel(
            name="SquidCastInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.squidrole"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.squidperson",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.squidmovie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SquidPersonToGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(db_index=True)),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.squidgenre",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.squidperson",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["genre", "count"], name="core_squidp_genre_i_39e30d_idx"
                    )
                ],
                "unique_together": {("person", "genre")},
            },
        ),
    ]
